#!/bin/bash

SAVED_LANG="$LANG"
LANG=C
ZENITY_ARGS=(--title="Brave Browser Launcher" --window-icon=brave-browser)
FIREJAIL=()
BRAVE_ARGS=(--enable-features=UseOzonePlatform --ozone-platform=wayland --incognito)

INSTALLED_VERSION="$(brave-browser --version 2>/dev/null | grep "Brave Browser" | tr -d " " | sed -E "s/BraveBrowser[0-9]+\.//g")"
LATEST_VERSION="$(curl -s https://brave-browser-downloads.s3.brave.com/latest/release.version)"
[[ $LATEST_VERSION =~ ^1\.[0-9]+\.[0-9]+$ ]] || exit 5

read -r -d $'\0' MSG_UPDATE_AVAILABLE <<EOM
<big><b>UPDATE AVAILABLE</b>

Please update brave.</big>

Installed version: $INSTALLED_VERSION
Latest version: $LATEST_VERSION
EOM

read -r -d $'\0' QST_START_OFFLINE <<EOM
Start brave with internet access?
EOM

if [[ "$INSTALLED_VERSION" != "$LATEST_VERSION" ]]; then
	zenity "${ZENITY_ARGS[@]}" --info --icon-name=software-update-available --ellipsize --text="$MSG_UPDATE_AVAILABLE"
fi

if command -v firejail >&-; then
	zenity "${ZENITY_ARGS[@]}" --question --default-cancel --icon-name=network-offline --ellipsize --text="$QST_START_OFFLINE"
	case $? in
		0)
			FIREJAIL=(firejail --ignore="net none")
		;;
		1)
			FIREJAIL=(firejail --net=none)
		;;
	esac
fi

LANG="$SAVED_LANG"
exec "${FIREJAIL[@]}" /usr/bin/brave-browser "${BRAVE_ARGS[@]}" "$@"
